name: PR Quality Gate

on:
  pull_request:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Run unit and integration tests with coverage
        env:
          GOTOOLCHAIN: go1.25.1
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Enforce 95% coverage on internal packages
        run: |
          coverage=$(awk 'BEGIN{FS="[ :\t]"} /^mode:/ {next} {path=$1; if (index(path, "/internal/") && index(path, "/internal/db/")==0) {n=$3; count=$4; total+=n; if (count>0) covered+=n}} END {if (total==0){print 0}else{printf "%.2f", covered/total*100}}' coverage.out)
          echo "Internal package coverage: ${coverage}%"
          awk -v cov="$coverage" 'BEGIN { if (cov+0 < 95) { printf "Coverage %.2f%% is below required 95%%\n", cov; exit 1 } }'
